variables:
  IMAGE_NAME: $DOCKER_USER/photographer-api


stages:
  - tests
  - build

run_tests:
    stage: tests
    image: gradle:7.5.1-jdk11-alpine
    script:
        - gradle test


build_image:
  stage: build
  image: docker
  services:
    - docker:22.06-rc-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME



