spring:
  servlet.multipart.max-file-size: 10GB
  servlet.multipart.max-request-size: 10GB

#  datasource:
#    url: jdbc:postgresql://photographer.c4m9wemgbmhh.us-east-1.rds.amazonaws.com:5432/photogapher
#    username: photographer
#    password: cub66901251
#    driverClassName: org.postgresql.Driver
#    jpa:
#      hibernate.ddl-auto: create
#      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
##        show-sql: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081